analytics:
  storage:
    type: elasticsearch
    url: "http://elasticsearch:9200"
    index_pattern: "metrics-{metric}"
    index_settings:
      number_of_shards: 1
      number_of_replicas: 1
    retention:
      enabled: true
      days: 30
  
  metrics:
    - name: request_duration_seconds
      type: histogram
      description: "HTTP request duration in seconds"
      labels:
        - endpoint
        - method
        - status
      unit: seconds
      aggregations:
        - avg
        - p95
        - p99
    
    - name: error_rate
      type: gauge
      description: "Application error rate"
      labels:
        - service
        - type
      unit: percent
      aggregations:
        - avg
        - max
    
    - name: active_users
      type: gauge
      description: "Number of active users"
      labels:
        - type
      aggregations:
        - avg
        - max
  
  reports:
    enabled: true
    schedule:
      daily:
        time: "00:00"
        metrics:
          - request_duration_seconds
          - error_rate
      weekly:
        day: monday
        time: "01:00"
        metrics:
          - active_users
    
    export:
      formats:
        - json
        - csv
        - pdf
      storage:
        type: s3
        bucket: "agnes-reports"
        prefix: "analytics"
  
  anomaly_detection:
    enabled: true
    algorithms:
      - type: zscore
        threshold: 3.0
      - type: moving_average
        window: 12
        threshold: 2.0
    
    alerts:
      enabled: true
      channels:
        - email
        - slack
  
  dashboards:
    enabled: true
    refresh_interval: 300
    default_timerange: 24h
    panels:
      - name: "Request Latency"
        metrics:
          - request_duration_seconds
        type: line
        aggregation: avg
      
      - name: "Error Rates"
        metrics:
          - error_rate
        type: line
        aggregation: avg
      
      - name: "User Activity"
        metrics:
          - active_users
        type: bar
        aggregation: max
