search:
  elasticsearch_url: "http://elasticsearch:9200"
  
  indices:
    products:
      settings:
        number_of_shards: 1
        number_of_replicas: 1
        analysis:
          analyzer:
            custom_analyzer:
              type: custom
              tokenizer: standard
              filter:
                - lowercase
                - stop
                - snowball
      mappings:
        properties:
          name:
            type: text
            analyzer: custom_analyzer
            fields:
              keyword:
                type: keyword
          description:
            type: text
            analyzer: custom_analyzer
          price:
            type: float
          categories:
            type: keyword
          tags:
            type: keyword
          created_at:
            type: date
          updated_at:
            type: date
    
    users:
      settings:
        number_of_shards: 1
        number_of_replicas: 1
      mappings:
        properties:
          username:
            type: keyword
          email:
            type: keyword
          full_name:
            type: text
          roles:
            type: keyword
          last_login:
            type: date
    
    documents:
      settings:
        number_of_shards: 1
        number_of_replicas: 1
      mappings:
        properties:
          title:
            type: text
            fields:
              keyword:
                type: keyword
          content:
            type: text
          file_type:
            type: keyword
          metadata:
            type: object
          permissions:
            type: keyword
  
  indexing:
    batch_size: 100
    refresh_interval: "1s"
    queue_size: 1000
  
  query:
    max_results: 100
    default_operator: "OR"
    minimum_should_match: "75%"
    highlight:
      pre_tags: ["<strong>"]
      post_tags: ["</strong>"]
      number_of_fragments: 3
      fragment_size: 150
  
  suggestions:
    enabled: true
    max_suggestions: 5
    min_prefix_length: 2
  
  monitoring:
    enabled: true
    metrics:
      - name: search_requests_total
        type: counter
        labels:
          - index
          - status
      - name: indexing_requests_total
        type: counter
        labels:
          - index
          - operation
